image: node:alpine
pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master
  variables:
  PUBLIC_URL: "/git@gitlab.com:Cheriaa/assessment-todo-app-part-2.git" # slash is important